#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal --output eDP-1 --mode 1366x768 --rotate normal --right-of HDMI-1
    bspc monitor HDMI-1 -d 1 2 3 4 5 6
    bspc monitor eDP-1 -d 7 8 9 0
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6
fi


bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color	    "#e5e9f0"
bspc config active_border_color	    "#ffcc33"
bspc config focused_border_color	"#2492e0"
bspc config presel_feedback_color	"#b48ead"
bspc config urgent_border_color 	"#ff4040"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# AUTOSTART

gsettings set org.gnome.desktop.interface gtk-theme rose-pine-gtk &
gsettings set org.gnome.desktop.interface color-scheme prefer-dark &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
udiskie &
udiskie -s &
kdeconnect-indicator &
syncthing &
nm-applet --indicator &
waypaper --restore &
alias ls="exa --icons --group-directories-first" & 
/home/lxbx/.config/polybar/launch.sh &

